
---
 - name: Ansible
   hosts: windows
#   become: true
   gather_facts: no
   tasks:

      - name: Download and install Chocolatey
      win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
     - name: Install firefox
  #   win_command: powershell.exe shutdown -s -t 1
       win_chocolatey:
           name: notepadplusplus.install
           state: present
     - name: Updates all choco packages
       win_chocolatey:
         name: all
         state: latest
