---
- name: install Apache
  become: true
  hosts: all

  tasks:

    - name: install Apache in ubuntu
      apt:
        name: apache2
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: install apache on centos
      yum:
        name: ["httpd", "firewalld"]
        state: present
        update_cache: true
      when: ansible_os_family == 'RedHat'

    - name: run apache
      service:
        name: apache2
        state: started
        enable: true
      when: ansible_os_family == 'Debian'

    - name: run apache centos
      service:
        name: httpd
        state: started
        enable: true
      when: ansible_os_family == 'RedHat'

    - name: os
      service: 
        name: httpd firewall
        state: started
        enable: true
      when: ansible_os_family == 'RedHat'
 
    - name: configure firewall
      command: firewall-cmd --permanent --add-service=http
      when: ansible_os_family == 'RedHat'

    - name: reload firewall
      command: firewall-cmd --reload
      when: ansible_os_family == 'RedHat'
